### PR TITLE
Fix SS58 encoding/decoding and add verification from pubkeys

### LINKED ISSUE #10: SS58 encoding/decoding is broken for prefix > 63
SS58 prefixes are actually uint16 with a very bizarre encoding. This only becomes apparent once you see a prefix > 63.

### PR DESCRIPTION
**Pull request by elliot-u410**
This PR is designed to be reviewed commit-by-commit.

  * SS58 prefixes are actually `uint16` with a very bizarre encoding. This only becomes apparent once you see a prefix > 63. This PR reimplements the SS58 handling based on the Rust implementation in `sp-core`.
  * Prior to this PR it was not possible to `Verify` using a public key only. That is, of course, the main reason to use `Verify` in the first place. This PR adds this functionality.

Note very little attempt was made at maintaining backwards compatibility.

Fixes #10 and #11

### CODE REVIEW

**Comment by mikiquantum** [comment]
@vedhavyas Do you have a bit of time to review this PR and see if we can get it in? I was going to open one myself to support sr25519 signature verification with only Public Keys and this one seems to address that.

**Comment by elliot-u410** [comment]
Feel free!

**Comment by vedhavyas** [comment]
@elliot-u410 Thank you for the contribution 🙏🏼

**Comment by elliot-u410** [comment]
@vedhavyas Noting that this change was not backwards compatible but the v1.0.4 released version number makes it seem that it was backwards compatible.

**Comment by vedhavyas** [comment]
updated the release now 👍🏼

**Comment by mikiquantum** [comment]
Awesome @vedhavyas & thanks @elliot-u410 !

**Pull request merged**
